name: Telegram Bot Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install g++ make wget git -y
        wget https://github.com/tdlib/td/archive/refs/tags/v1.8.0.tar.gz
        tar -xvzf v1.8.0.tar.gz
        cd td-1.8.0 && mkdir build && cd build
        cmake .. && cmake --build . --target install
        pip install -r requirements.txt

    - name: Run the bot
      run: |
        python main.py
